### ISSUE TITLE
Integrate github rust wrapper

### ISSUE THREAD

**Issue by acmcarther** [acmcarther/catalyst#3]
https://github.com/acmcarther/github_v3_rust

**Comment by acmcarther** [comment]
test: pt r?

**Comment by acmcarther** [comment]
issue comment.

**Comment by acmcarther** [comment]
webhook test comment

**Comment by acmcarther** [comment]
Looks like this is sorta done.

Test catalyst bot pt r?

**Comment by acmcarther** [comment]
My bad, forgot to enable the webhook.

We're go for launch! 
pt r?

**Comment by pt-195** [comment]
PTBOT: Assigning @acmcarther to this PR

**Comment by acmcarther** [comment]
heh I used the wrong field. Pt bot do it again.

pt r?

**Comment by pt-195** [comment]
PTBOT: Assigning @acmcarther to this PR

**Comment by acmcarther** [comment]
last test pt r?

**Comment by pt-195** [comment]
PTBOT: Assigning @acmcarther to this PR

**Comment by acmcarther** [comment]
testing catalyst hosted remotely pt r?

**Comment by pt-195** [comment]
PTBOT: Assigning @acmcarther to this PR
